version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app/
    command: bash -c "python manage.py migrate && gunicorn docker_django.wsgi:application -w 2 -b :8000"


  db:
    image: postgres/postgres:latest
    env_file:
      - .env
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      #- POSTGRES_DB=ok
      #- POSTGRES_USER=postgres
      #- POSTGRES_PASSWORD=postgres
      #- ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
    restart: on-failure
    ports:
      - "5432:5432"
    expose:
      - 5432
