version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app/
    command: bash -c "sleep 2 && python manage.py migrate && gunicorn steps.wsgi:application -w 2 -b :8000"


  db:
    image: postgres:latest
    env_file:
      - .env
    restart: on-failure
    #ports:
    #  - "5432:5432"
    expose:
      - 5432
