# Generated by Django 4.1.3 on 2022-11-05 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Чуство")),
            ],
            options={
                "verbose_name": "Чувсто",
                "verbose_name_plural": "Чувства",
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[("NA", "АН"), ("AA", "АА")],
                        default="NA",
                        max_length=4,
                        verbose_name="Программа",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(blank=True, verbose_name="Номер"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Шаг",
                "verbose_name_plural": "Шаги",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(blank=True, verbose_name="Номер"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guide.step",
                        verbose_name="Шаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(blank=True, verbose_name="Номер"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текст вопроса"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guide.section",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["section__number", "number"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situation",
                    models.TextField(blank=True, null=True, verbose_name="Ситуация"),
                ),
                (
                    "thoughts",
                    models.TextField(blank=True, null=True, verbose_name="Мысли"),
                ),
                (
                    "actions",
                    models.TextField(blank=True, null=True, verbose_name="Действия"),
                ),
                (
                    "feelings",
                    models.ManyToManyField(
                        blank=True, to="guide.feeling", verbose_name="Чувства"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guide.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
    ]
