# Generated by Django 4.1.3 on 2022-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={
                "ordering": ["number"],
                "verbose_name": "Шаг",
                "verbose_name_plural": "Шаги",
            },
        ),
        migrations.RemoveField(
            model_name="step",
            name="order",
        ),
        migrations.AddField(
            model_name="step",
            name="number",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Номер"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="step",
            name="program",
            field=models.CharField(
                choices=[("NA", "АН"), ("AA", "АА")],
                default="NA",
                max_length=4,
                verbose_name="Программа",
            ),
        ),
    ]
