# Generated by Django 4.1.3 on 2022-11-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["section__step__number", "section__number", "number"],
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["step__number", "number"],
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
            },
        ),
        migrations.AlterField(
            model_name="question",
            name="number",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, verbose_name="Номер"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="number",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, verbose_name="Номер"
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="number",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, verbose_name="Номер"
            ),
        ),
    ]
