# Generated by Django 4.1.3 on 2022-11-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_alter_step_options_remove_step_order_step_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="number",
            field=models.PositiveSmallIntegerField(blank=True, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="step",
            name="number",
            field=models.PositiveSmallIntegerField(blank=True, verbose_name="Номер"),
        ),
    ]
