# Generated by Django 4.1.3 on 2022-11-06 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("guide", "0004_answer_feelings2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата и время"
            ),
        ),
        migrations.CreateModel(
            name="AnswerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("WORK", "В работе"), ("COMPLETED", "Завершен")],
                        default="WORK",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guide.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус ответа",
                "verbose_name_plural": "Статусы ответа",
            },
        ),
    ]
