# Generated by Django 4.1.3 on 2022-11-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0005_alter_answer_created_answerstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="show_header",
            field=models.BooleanField(
                default=True, verbose_name="Показывать заголовок"
            ),
        ),
    ]
