# Generated by Django 4.1.3 on 2022-11-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0007_feeling_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="feelings2",
        ),
    ]
