# Generated by Django 4.1.3 on 2022-11-12 10:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0008_remove_answer_feelings2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Текст вопроса"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="text",
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="step",
            name="program",
            field=models.CharField(
                choices=[("NA", "Шаги АН по руководству"), ("AA", "Шаги АА")],
                default="NA",
                max_length=4,
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="text",
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name="Текст"),
        ),
    ]
