# Generated by Django 4.1.3 on 2022-11-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0009_alter_question_text_alter_section_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="publish",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Опубликовать в примерах"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="show_on_site",
            field=models.BooleanField(default=False, verbose_name="Прошло модерацию"),
        ),
    ]
