# Generated by Django 4.1.3 on 2022-11-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0010_answer_publish_answer_show_on_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="publish",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Опубликовать в примерах"
            ),
        ),
    ]
