# Generated by Django 4.1.3 on 2022-11-12 12:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0010_answer_publish_answer_show_on_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="post_text",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Текст после вопроса"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="pre_text",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Текст перед вопроса"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="publish",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Опубликовать в примерах",
                verbose_name="Опубликовать в примерах",
            ),
        ),
    ]
