# Generated by Django 4.1.3 on 2022-11-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0011_question_post_text_question_pre_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="show_header",
        ),
    ]
