# Generated by Django 4.1.3 on 2022-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0013_remove_section_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="publish",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Опубликовать свой пример для помощи другим зависимым с пониманием вопроса",
                verbose_name="Опубликовать",
            ),
        ),
    ]
