# Generated by Django 4.1.3 on 2022-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0014_alter_answer_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст вопроса"),
        ),
    ]
