# Generated by Django 4.1.3 on 2022-11-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0016_alter_question_pre_text_answervote"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("section", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("step", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="step",
            unique_together={("program", "number")},
        ),
    ]
