# Generated by Django 4.1.3 on 2022-12-08 01:17

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0016_alter_question_pre_text_answervote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sect",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "text",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
            },
        ),
        migrations.AddField(
            model_name="step",
            name="sect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="guide.sect",
                verbose_name="Программа",
            ),
        ),
    ]
