# Generated by Django 4.1.3 on 2022-12-08 01:17

from django.db import migrations


def convert_program_to_sect(apps, schema_editor):
    Step = apps.get_model('guide', 'Step')
    Sect = apps.get_model('guide', 'Sect')

    for step in Step.objects.all():
        sect, _ = Sect.objects.get_or_create(id=step.program, title=step.program)
        step.sect = sect
        step.save()


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0017_sect_step_sect"),
    ]

    operations = [migrations.RunPython(convert_program_to_sect)]
