# Generated by Django 4.1.3 on 2022-12-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0018_auto_20221208_0417"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="program",
        ),
    ]
