# Generated by Django 4.1.3 on 2022-12-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0020_sect_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="seo_description",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="seo_h1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="seo_title",
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
        migrations.AddField(
            model_name="sect",
            name="seo_description",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="sect",
            name="seo_h1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sect",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sect",
            name="seo_title",
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="seo_description",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="seo_h1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="seo_title",
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
        migrations.AddField(
            model_name="step",
            name="seo_description",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="step",
            name="seo_h1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="step",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="step",
            name="seo_title",
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
    ]
