# Generated by Django 4.1.3 on 2022-12-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0021_question_seo_description_question_seo_h1_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("section", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("step", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="step",
            unique_together={("sect", "number")},
        ),
    ]
