# Generated by Django 4.1.3 on 2022-12-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=68, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=155, null=True),
                ),
                ("keywords", models.CharField(blank=True, max_length=255, null=True)),
                ("h1", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Мета теги",
                "verbose_name_plural": "Мета теги",
            },
        ),
    ]
